require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
-- require "user.lsp"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.impatient"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.file_browser"
require "user.blankline"
require "user.obsidian"

vim.api.nvim_set_hl(0, 'LineNr', { fg = "#D26466"})

